all: learning chanting

learning:
	lualatex -interaction=nonstopmode -halt-on-error -output-directory=../charts/ patimokkha-learning-chart.tex

chanting:
	lualatex -interaction=nonstopmode -halt-on-error -output-directory=../charts/ patimokkha-chanting-chart.tex
